#!/bin/bash
# set -euo pipefail

loopcnt=5000

# normal version
bin_norm=./iny
# optimized version (asm, static.. no libc, no main(), etc.) :)
bin_opt=./iny-raw

echo "Benchmarking '$bin_opt' and '$bin_norm' with $loopcnt runs each..."
echo

if [[ ! -f "$bin_norm" || ! -x "$bin_norm" ]]; then
	echo "Couldn't find $bin_norm. Run me (tests/test-timing) from main dir" >&2
	exit
fi

time_run() {
    local cmd=$1
    local label=$2

    echo "Running: $label"
    local start end

    start=$(date +%s.%N)

    for ((i = 0; i < loopcnt; i++)); do
        echo | "$cmd" # > /dev/null
    done

    end=$(date +%s.%N)

    duration=$(echo "$end - $start" | bc)
    echo "$label: $duration seconds"
    echo
}

time_run "$bin_opt" "$bin_opt (no-libc, static)"
time_run "$bin_norm" "$bin_norm (libc)"

